config/routes.rb
Rails.application.routes.draw do
  resources :usuarios
  root to: 'professionals#index'

  devise_for :users
  resources :professionals do
    resources :appointments do
      post :delete_all, on: :collection #Para elimintar todos los turnos de un professional
    end

  end

  post '/usuarios/new', to:'usuarios#create'
  post '/usuarios/:id/edit' , to:'usuarios#update'

  resources :export
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/professional.rb
class Professional < ApplicationRecord
    has_many :appointments, dependent: :restrict_with_error
    validates :name, presence:{message: "El nombre es obligatorio."}, uniqueness: {message: "El nombre de profesional no puede repetirse."}
end

app/controllers/professionals_controller.rb
class ProfessionalsController < ApplicationController
  load_and_authorize_resource
  #before_action :set_professional, only: [:show, :edit, :update, :destroy]

  # GET /professionals
  def index
    @professionals = Professional.all
  end

  # GET /professionals/1
  def show
  end

  # GET /professionals/new
  def new
    @professional = Professional.new
  end

  # GET /professionals/1/edit
  def edit
  end

  # POST /professionals
  def create
      @professional = Professional.new(professional_params)

      if @professional.save
        redirect_to @professional, notice: 'El profesional '+professional_params[:name]+' fue creado exitosamente.'
      else
        render :new
      end
  end

  # PATCH/PUT /professionals/1
  def update
    if @professional.update(professional_params)
      redirect_to @professional, notice: 'Professional was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /professionals/1
  def destroy
      if @professional.destroy
        redirect_to professionals_url, notice: 'El profesional '+@professional.name+' fue eliminado correctamente.'
      else
        redirect_to professionals_url, notice: 'El profesional '+@professional.name+' tiene turnos asociados. No pudo eliminarse.'
      end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_professional
      @professional = Professional.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def professional_params
      params.require(:professional).permit(:name)
    end

end

app/helpers/professionals_helper.rb
module ProfessionalsHelper

end

app/views/professionals/_form.html.erb
<%= form_with(model: professional) do |form| %>
  <% if professional.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(professional.errors.count, "error") %> prohibited this professional from being saved:</h2>

      <ul>
        <% professional.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/professionals/edit.html.erb
<h1>Editing Professional</h1>

<%= render 'form', professional: @professional %>

<%= link_to 'Show', @professional %> |
<%= link_to 'Back', professionals_path %>

app/views/professionals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Professionals</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @professionals.each do |professional| %>
      <tr>
        <td><%= professional.name %></td>
        <td><%= link_to 'Ver', professional %></td>
        <td><%= link_to 'Appointments', professional_appointments_path(professional) %></td>
        <% if can? :manage, Professional %>
        <td><%= link_to 'Modificar', edit_professional_path(professional) %></td>
        <td><%= link_to 'Eliminar', professional, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if can? :manage, Professional %>
<%= link_to 'New Professional', new_professional_path %>
<% end%>

app/views/professionals/new.html.erb
<h1>New Professional</h1>

<%= render 'form', professional: @professional %>

<%= link_to 'Back', professionals_path %>

app/views/professionals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @professional.name %>
</p>
<% if can? :manage, Professional %>
<%= link_to 'Edit', edit_professional_path(@professional) %> |
<% end %>
<%= link_to 'Back', professionals_path %>