config/routes.rb
Rails.application.routes.draw do
  resources :usuarios
  root to: 'professionals#index'

  devise_for :users
  resources :professionals do
    resources :appointments do
      post :delete_all, on: :collection #Para elimintar todos los turnos de un professional
    end

  end

  post '/usuarios/new', to:'usuarios#create'
  post '/usuarios/:id/edit' , to:'usuarios#update'

  resources :export
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  #load_and_authorize_resource
  before_action :set_usuario, only: [:show, :edit, :update, :destroy]

  # GET /usuarios
  def index
    @usuarios = User.all
    authorize! :read, @usuarios
  end

  # GET /usuarios/1
  def show
  end

  # GET /usuarios/new
  def new
    @usuario = User.new
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios
  def create
    @usuario = User.new(usuario_params)

    if @usuario.save
      redirect_to usuarios_url, notice: 'Se creó el usuario correctamente.'
    else
      render :new
    end
  end

  # PATCH/PUT /usuarios/1
  def update
    if @usuario.update(usuario_params)
      redirect_to usuarios_url, notice: 'Se modificó el usuario correctamente.'
    else
      render :edit
    end
  end

  # DELETE /usuarios/1
  def destroy
    @usuario.destroy
    redirect_to usuarios_url, notice: 'Usuario was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def usuario_params
      params.require(:usuario).permit(:email, :password, :role)
    end
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/usuarios/_form.html.erb
<%= form_for :usuario do |form| %>
  <% if usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
        <% usuario.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>
  <%if request.original_url.include?("new") %>
  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>
  <% end %>

  <div class="field">
    <%= form.label :Rol %>
    <%= form.select :role, options_for_select(["consulta","asistencia","administracion"], :selected=> usuario.role )%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/usuarios/edit.html.erb
<h1>Editar usuario</h1>

<%= render 'form', usuario: @usuario %>

<%= link_to 'Volver', usuarios_path %>

app/views/usuarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Usuarios</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Rol</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usuarios.each do |usuario| %>
      <tr>
        <td><%= usuario.email %></td>
        <td><%= usuario.role %></td>
        <td><%= link_to 'Editar', edit_usuario_path(usuario) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Usuario', new_usuario_path %>

app/views/usuarios/new.html.erb
<h1>Nuevo usuario</h1>

<%= render 'form', usuario: @usuario %>

<%= link_to 'Volver', usuarios_path %>

app/views/usuarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @usuario.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @usuario.password %>
</p>

<p>
  <strong>Role:</strong>
  <%= @usuario.role %>
</p>

<%= link_to 'Edit', edit_usuario_path(@usuario) %> |
<%= link_to 'Back', usuarios_path %>