config/routes.rb
Rails.application.routes.draw do
  resources :usuarios
  root to: 'professionals#index'

  devise_for :users
  resources :professionals do
    resources :appointments do
      post :delete_all, on: :collection #Para elimintar todos los turnos de un professional
    end

  end

  post '/usuarios/new', to:'usuarios#create'
  post '/usuarios/:id/edit' , to:'usuarios#update'

  resources :export
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :professional

  validates :date, presence: true, uniqueness: {scope: :professional, message: "El turno ya se encuentra tomado para ese profesional."}, length: {minimum: 2}
  validates :name, presence: true
  validates :surname, presence: true
  validates :phone, presence: true, numericality: true, length: {minimum: 8, maximum: 15}

  validate :past_date
  validate :right_time,

  def past_date
    if(date < DateTime.now)
      errors.add(:date, "La fecha ingresada es pasada.")
    end
  end

  def right_time #valida que la hora del turno sea correcto (hora en punto de 8 a 17 hs.)
    time = date.strftime("%H:%M")
    turnos =['08:00','09:00','10:00','11:00','12:00','13:00','14:00','15:00','16:00','17:00',]
    if(!turnos.include?(time))
      errors.add(:date, "La hora elegida es incorrecta. Debe ser hora exacta entre 08:00 a 17:00.")
    end
  end

end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  load_and_authorize_resource
  before_action :set_professional
  #before_action :set_appointment, only: [:show, :edit, :update, :destroy]

  # GET /appointments
  def index
    if params[:fecha].present?
      fecha=Date.parse(params[:fecha])
      @appointments = Appointment.where(:date=> fecha.beginning_of_day..fecha.end_of_day, professional: @professional)
    else
      @appointments = @professional.appointments
    end 
  end

  # GET /appointments/1
  def show
  end

  # GET /appointments/new
  def new
    @appointment = @professional.appointments.new
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments
  def create
    @appointment = @professional.appointments.new(appointment_params)

    if @appointment.save
      redirect_to [@appointment.professional, @appointment], notice: 'Appointment was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /appointments/1
  def update
    if @appointment.update(appointment_params)
      redirect_to [@appointment.professional, @appointment], notice: 'Appointment was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /appointments/1
  def destroy
    @appointment.destroy
    redirect_to professional_appointments_url, notice: 'Se canceló el turno correctamente.'
  end

  #DELETE ALL
  def delete_all
    @professional.appointments.destroy_all
    redirect_to professional_appointments_url, notice: 'Se cancelaron todos los turnos.'
  end


  private
    def set_professional
      @professional = Professional.find(params[:professional_id])  
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = @professional.appointments.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def appointment_params
      params.require(:appointment).permit(:date, :name, :surname, :phone, :notes, :belongs_to)
    end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_form.html.erb
<%= form_with(model: [@professional, appointment]) do |form| %>
  <% if appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
        <% appointment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date %>
    <%= form.datetime_local_field :date %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :surname %>
    <%= form.text_field :surname %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :notes %>
    <%= form.text_field :notes %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/appointments/edit.html.erb
<h1>Editing Appointment</h1>

<%= render 'form', appointment: @appointment%>

<%= link_to 'Show', [@professional, @appointment] %> |
<%= link_to 'Back', professional_appointments_path(@professional) %>

app/views/appointments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Appointments</h1>
<%= form_tag({controller: :appointments, action: :index}, {method: :get}) do  %>
  <%= date_field_tag :fecha %>
  <%=submit_tag "Filtrar por fecha", name: nil %>
  <% end %>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Name</th>
      <th>Surname</th>
      <th>Phone</th>
      <th>Notes</th>
      <th>Professional</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <td><%= appointment.date %></td>
        <td><%= appointment.name %></td>
        <td><%= appointment.surname %></td>
        <td><%= appointment.phone %></td>
        <td><%= appointment.notes %></td>
        <td><%= appointment.professional.name %></td>
        <td><%= link_to 'Ver', [@professional, appointment] %></td>
        <% if can? :manage, Appointment %>
        <td><%= link_to 'Modificar', edit_professional_appointment_path(@professional, appointment) %></td>
        <td><%= link_to 'Cancelar turno', [@professional, appointment], method: :delete, data: { confirm: '¿Seguro que desea cancelar el turno?' } %></td>
        <% end %>
        </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if can? :manage, Appointment %>
<%= link_to 'New Appointment', new_professional_appointment_path(@professional) %>
<%= link_to 'Cancelar todos los turnos', delete_all_professional_appointments_path, method: :post, data: { confirm: '¿Seguro que desea cancelar todos los turnos?' } %>
<% end %>
<%= link_to 'Back', professionals_path %>

app/views/appointments/new.html.erb
<h1>New Appointment</h1>

<%= render 'form', appointment: @appointment %>

<%= link_to 'Back', professional_appointments_path(@professional) %>

app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @appointment.date %>
</p>

<p>
  <strong>Name:</strong>
  <%= @appointment.name %>
</p>

<p>
  <strong>Surname:</strong>
  <%= @appointment.surname %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @appointment.phone %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @appointment.notes %>
</p>

<p>
  <strong>Profesional:</strong>
  <%= @appointment.professional.name %>
</p>
<% if can? :manage, Appointment %>
<%= link_to 'Edit', edit_professional_appointment_path(@professional, @appointment) %> |
<% end %>
<%= link_to 'Back', professional_appointments_path(@professional) %>